export const ACTIONTYPES = {
  START_GAME: "START_GAME",
  SET_QUESTIONS: "SET_QUESTIONS",
  SET_QUESTION_INDEX: "SET_QUESTION_INDEX",
  SET_INDEX_ARRAY: "SET_INDEX_ARRAY",
  SET_DISABLE_BUTTON: "SET_DISABLE_BUTTON",
  SET_IS_BACKGROUND_CHANGED: "SET_IS_BACKGROUND_CHANGED",
  SET_INCREASE_SCORE: "SET_INCREASE_SCORE",
  SET_LANGUAGE: "SET_LANGUAGE",
  SET_DECREASE_SCORE: "SET_DECREASE_SCORE",
  SET_GAME_TIMER: "SET_GAME_TIMER",
  SET_QUESTION_TIMER: "SET_QUESTION_TIMER",
  SET_QUESTION_TIME: "SET_QUESTION_TIME",
  SET_IS_ARRAY_SHUFFLED: "SET_IS_ARRAY_SHUFFLED",
  RESET_QUESTION_TIMER: "RESET_QUESTION_TIMER",
  SET_DISPLAY_MINUTES: "SET_DISPLAY_MINUTES",
  SET_DISPLAY_SECONDS: "SET_DISPLAY_SECONDS"
};
